import { MODULE_NAME } from './constants';

export const REMOVE_FAVORITE = `${MODULE_NAME}.REMOVE_FAVORITE`;
export const ADD_FAVORITE = `${MODULE_NAME}.ADD_FAVORITE`;
export const REMOVE_ALL_CRYPTOS = `${MODULE_NAME}.REMOVE_ALL_CRYPTOS`;
export const GET_COINS = `${MODULE_NAME}.GET_COIN`;
export const GET_COINS_SUCCESS = `${MODULE_NAME}.GET_COIN_SUCCESS`;
export const GET_COINS_FAILURE = `${MODULE_NAME}.GET_COIN_FAILURE`;
export const GET_DATA = `${MODULE_NAME}.GET_DATA`;
export const GET_COIN_HISTORY = `${MODULE_NAME}.GET_COIN_HISTORY`;
export const HOME_LOADING = `${MODULE_NAME}.HOME_LOADING`;
export const HOME_LOADING_DONE = `${MODULE_NAME}.HOME_LOADING_DONE`;
